import { Prettify } from "@/lib/utils";

export type AffixType = "prefix" | "root" | "suffix";

export type Affix = {
  label: string;
  value: string;
  type: AffixType;
  definition: string;
  examples: string[];
};

export type Prefix = Prettify<
  Affix & {
    type: "prefix";
  }
>;

export type Root = Prettify<
  Affix & {
    type: "root";
  }
>;

export type Suffix = Prettify<
  Affix & {
    type: "suffix";
  }
>;

export const prefixes: Prefix[] = [
  {
    label: "anti-",
    value: "anti",
    type: "prefix",
    definition: "against",
    examples: ["anticlimax"],
  },
  {
    label: "de-",
    value: "de",
    type: "prefix",
    definition: "opposite",
    examples: ["devalue"],
  },
  {
    label: "dis-",
    value: "dis",
    type: "prefix",
    definition: "not; opposite of",
    examples: ["discover"],
  },
  {
    label: "en-",
    value: "en",
    type: "prefix",
    definition: "cause to",
    examples: ["enact"],
  },
  {
    label: "em-",
    value: "em",
    type: "prefix",
    definition: "cause to",
    examples: ["empower"],
  },
  {
    label: "fore-",
    value: "fore",
    type: "prefix",
    definition: "before; front of",
    examples: ["foreshadow", "forearm"],
  },
  {
    label: "in-",
    value: "in",
    type: "prefix",
    definition: "in",
    examples: ["income"],
  },
  {
    label: "im-",
    value: "im",
    type: "prefix",
    definition: "in",
    examples: ["impulse"],
  },
  {
    label: "in-",
    value: "in",
    type: "prefix",
    definition: "not",
    examples: ["indirect"],
  },
  {
    label: "im-",
    value: "im",
    type: "prefix",
    definition: "not",
    examples: ["immoral"],
  },
  {
    label: "il-",
    value: "il",
    type: "prefix",
    definition: "not",
    examples: ["illiterate"],
  },
  {
    label: "ir-",
    value: "ir",
    type: "prefix",
    definition: "not",
    examples: ["irreverent"],
  },
  {
    label: "inter-",
    value: "inter",
    type: "prefix",
    definition: "between; among",
    examples: ["interrupt"],
  },
  {
    label: "mid-",
    value: "mid",
    type: "prefix",
    definition: "middle",
    examples: ["midfield"],
  },
  {
    label: "mis-",
    value: "mis",
    type: "prefix",
    definition: "wrongly",
    examples: ["misspell"],
  },
  {
    label: "non-",
    value: "non",
    type: "prefix",
    definition: "not",
    examples: ["nonviolent"],
  },
  {
    label: "over-",
    value: "over",
    type: "prefix",
    definition: "over; too much",
    examples: ["overeat"],
  },
  {
    label: "pre-",
    value: "pre",
    type: "prefix",
    definition: "before",
    examples: ["preview"],
  },
  {
    label: "re-",
    value: "re",
    type: "prefix",
    definition: "again",
    examples: ["rewrite"],
  },
  {
    label: "semi-",
    value: "semi",
    type: "prefix",
    definition: "half; partly; not fully",
    examples: ["semifinal"],
  },
  {
    label: "sub-",
    value: "sub",
    type: "prefix",
    definition: "under",
    examples: ["subway"],
  },
  {
    label: "super-",
    value: "super",
    type: "prefix",
    definition: "above; beyond",
    examples: ["superhuman"],
  },
  {
    label: "trans-",
    value: "trans",
    type: "prefix",
    definition: "across",
    examples: ["transmit"],
  },
  {
    label: "un-",
    value: "un",
    type: "prefix",
    definition: "not; opposite of",
    examples: ["unusual"],
  },
  {
    label: "under-",
    value: "under",
    type: "prefix",
    definition: "under; too little",
    examples: ["underestimate"],
  },
];

export const roots: Root[] = [
  {
    label: "ambi",
    value: "ambi",
    type: "root",
    definition: "both",
    examples: ["ambiguous", "ambidextrous"],
  },
  {
    label: "aqua",
    value: "aqua",
    type: "root",
    definition: "water",
    examples: ["aquarium", "aquamarine"],
  },
  {
    label: "aud",
    value: "aud",
    type: "root",
    definition: "to hear",
    examples: ["audience", "audition"],
  },
  {
    label: "bene",
    value: "bene",
    type: "root",
    definition: "good",
    examples: ["benefactor", "benevolent"],
  },
  {
    label: "cent",
    value: "cent",
    type: "root",
    definition: "one hundred",
    examples: ["century", "percent"],
  },
  {
    label: "circum",
    value: "circum",
    type: "root",
    definition: "around",
    examples: ["circumference", "circumstance"],
  },
  {
    label: "contra",
    value: "contra",
    type: "root",
    definition: "against",
    examples: ["contradict"],
  },
  {
    label: "counter",
    value: "counter",
    type: "root",
    definition: "against",
    examples: ["encounter"],
  },
  {
    label: "dict",
    value: "dict",
    type: "root",
    definition: "to say",
    examples: ["dictation", "dictator"],
  },
  {
    label: "duc",
    value: "duc",
    type: "root",
    definition: "to lead",
    examples: ["conduct"],
  },
  {
    label: "duct",
    value: "duct",
    type: "root",
    definition: "to lead",
    examples: ["induce"],
  },
  {
    label: "fac",
    value: "fac",
    type: "root",
    definition: "to do; to make",
    examples: ["factory", "manufacture"],
  },
  {
    label: "form",
    value: "form",
    type: "root",
    definition: "shape",
    examples: ["conform", "reform"],
  },
  {
    label: "fort",
    value: "fort",
    type: "root",
    definition: "strength",
    examples: ["fortitude", "fortress"],
  },
  {
    label: "fract",
    value: "fract",
    type: "root",
    definition: "to break",
    examples: ["fracture", "fraction"],
  },
  {
    label: "ject",
    value: "ject",
    type: "root",
    definition: "throw",
    examples: ["projection", "rejection"],
  },
  {
    label: "jud",
    value: "jud",
    type: "root",
    definition: "judge",
    examples: ["judicial", "prejudice"],
  },
  {
    label: "mal",
    value: "mal",
    type: "root",
    definition: "bad",
    examples: ["malevolent", "malefactor"],
  },
  {
    label: "mater",
    value: "mater",
    type: "root",
    definition: "mother",
    examples: ["material", "maternity"],
  },
  {
    label: "mit",
    value: "mit",
    type: "root",
    definition: "to send",
    examples: ["transmit", "admit"],
  },
  {
    label: "mort",
    value: "mort",
    type: "root",
    definition: "death",
    examples: ["mortal", "mortician"],
  },
  {
    label: "multi",
    value: "multi",
    type: "root",
    definition: "many",
    examples: ["multimedia", "multiple"],
  },
  {
    label: "pater",
    value: "pater",
    type: "root",
    definition: "father",
    examples: ["paternal", "paternity"],
  },
  {
    label: "port",
    value: "port",
    type: "root",
    definition: "to carry",
    examples: ["portable", "transportation"],
  },
  {
    label: "rupt",
    value: "rupt",
    type: "root",
    definition: "to break",
    examples: ["bankrupt", "disruption"],
  },
  {
    label: "scrib",
    value: "scrib",
    type: "root",
    definition: "to write",
    examples: ["inscription"],
  },
  {
    label: "scribe",
    value: "scribe",
    type: "root",
    definition: "to write",
    examples: ["prescribe"],
  },
  {
    label: "sect",
    value: "sect",
    type: "root",
    definition: "to cut",
    examples: ["section"],
  },
  {
    label: "sec",
    value: "sec",
    type: "root",
    definition: "to cut",
    examples: ["bisect"],
  },
  {
    label: "sent",
    value: "sent",
    type: "root",
    definition: "to feel; to send",
    examples: ["consent", "resent"],
  },
  {
    label: "spect",
    value: "spect",
    type: "root",
    definition: "to look",
    examples: ["inspection", "spectator"],
  },
  {
    label: "struct",
    value: "struct",
    type: "root",
    definition: "to build",
    examples: ["destruction", "restructure"],
  },
  {
    label: "vid",
    value: "vid",
    type: "root",
    definition: "to see",
    examples: ["video"],
  },
  {
    label: "vis",
    value: "vis",
    type: "root",
    definition: "to see",
    examples: ["televise"],
  },
  {
    label: "voc",
    value: "voc",
    type: "root",
    definition: "voice; to call",
    examples: ["vocalize", "advocate"],
  },
  {
    label: "anthropo",
    value: "anthropo",
    type: "root",
    definition: "man; human; humanity",
    examples: ["anthropologist", "philanthropy"],
  },
  {
    label: "auto",
    value: "auto",
    type: "root",
    definition: "self",
    examples: ["autobiography", "automobile"],
  },
  {
    label: "bio",
    value: "bio",
    type: "root",
    definition: "life",
    examples: ["biology", "biography"],
  },
  {
    label: "chron",
    value: "chron",
    type: "root",
    definition: "time",
    examples: ["chronological", "chronic"],
  },
  {
    label: "dyna",
    value: "dyna",
    type: "root",
    definition: "power",
    examples: ["dynamic", "dynamite"],
  },
  {
    label: "dys",
    value: "dys",
    type: "root",
    definition: "bad; hard; unlucky",
    examples: ["dysfunctional", "dyslexic"],
  },
  {
    label: "gram",
    value: "gram",
    type: "root",
    definition: "thing written",
    examples: ["epigram", "telegram"],
  },
  {
    label: "graph",
    value: "graph",
    type: "root",
    definition: "writing",
    examples: ["graphic", "phonograph"],
  },
  {
    label: "hetero",
    value: "hetero",
    type: "root",
    definition: "different",
    examples: ["heteronym", "heterogeneous"],
  },
  {
    label: "homo",
    value: "homo",
    type: "root",
    definition: "same",
    examples: ["homonym", "homogenous"],
  },
  {
    label: "hydr",
    value: "hydr",
    type: "root",
    definition: "water",
    examples: ["hydration", "dehydrate"],
  },
  {
    label: "hypo",
    value: "hypo",
    type: "root",
    definition: "below; beneath",
    examples: ["hypothermia", "hypothetical"],
  },
  {
    label: "logy",
    value: "logy",
    type: "root",
    definition: "study of",
    examples: ["biology", "psychology"],
  },
  {
    label: "meter",
    value: "meter",
    type: "root",
    definition: "measure",
    examples: ["thermometer"],
  },
  {
    label: "metr",
    value: "metr",
    type: "root",
    definition: "measure",
    examples: ["perimeter", "metrics"],
  },
  {
    label: "micro",
    value: "micro",
    type: "root",
    definition: "small",
    examples: ["microbe", "microscope"],
  },
  {
    label: "mis",
    value: "mis",
    type: "root",
    definition: "hate",
    examples: ["misanthrope"],
  },
  {
    label: "miso",
    value: "miso",
    type: "root",
    definition: "hate",
    examples: ["misogyny"],
  },
  {
    label: "mono",
    value: "mono",
    type: "root",
    definition: "one",
    examples: ["monologue", "monotonous"],
  },
  {
    label: "morph",
    value: "morph",
    type: "root",
    definition: "form; shape",
    examples: ["morphology", "morphing"],
  },
  {
    label: "nym",
    value: "nym",
    type: "root",
    definition: "name",
    examples: ["antonym", "synonym"],
  },
  {
    label: "phil",
    value: "phil",
    type: "root",
    definition: "love",
    examples: ["philanthropist", "philosophy"],
  },
  {
    label: "phobia",
    value: "phobia",
    type: "root",
    definition: "fear",
    examples: ["claustrophobia", "phobic"],
  },
  {
    label: "phon",
    value: "phon",
    type: "root",
    definition: "sound",
    examples: ["phone", "symphony"],
  },
  {
    label: "photo",
    value: "photo",
    type: "root",
    definition: "light",
    examples: ["photograph"],
  },
  {
    label: "phos",
    value: "phos",
    type: "root",
    definition: "light",
    examples: ["phosphorous"],
  },
  {
    label: "pseudo",
    value: "pseudo",
    type: "root",
    definition: "false",
    examples: ["pseudonym", "pseudoscience"],
  },
  {
    label: "psycho",
    value: "psycho",
    type: "root",
    definition: "soul; spirit",
    examples: ["psychology", "psychic"],
  },
  {
    label: "scope",
    value: "scope",
    type: "root",
    definition: "viewing instrument",
    examples: ["microscope", "telescope"],
  },
  {
    label: "techno",
    value: "techno",
    type: "root",
    definition: "art; science; skill",
    examples: ["technique", "technological"],
  },
  {
    label: "tele",
    value: "tele",
    type: "root",
    definition: "far off",
    examples: ["television", "telephone"],
  },
  {
    label: "therm",
    value: "therm",
    type: "root",
    definition: "heat",
    examples: ["thermal", "thermometer"],
  },
];

export const suffixes: Suffix[] = [
  {
    label: "-able",
    value: "able",
    type: "suffix",
    definition: "is; can be",
    examples: ["affordable"],
  },
  {
    label: "-ible",
    value: "ible",
    type: "suffix",
    definition: "is; can be",
    examples: ["sensible"],
  },
  {
    label: "-al",
    value: "al",
    type: "suffix",
    definition: "having characteristics of",
    examples: ["universal"],
  },
  {
    label: "-ial",
    value: "ial",
    type: "suffix",
    definition: "having characteristics of",
    examples: ["facial"],
  },
  {
    label: "-ed",
    value: "ed",
    type: "suffix",
    definition: "past tense verbs; adjectives",
    examples: ["walked"],
  },
  {
    label: "-en",
    value: "en",
    type: "suffix",
    definition: "made of",
    examples: ["golden"],
  },
  {
    label: "-er",
    value: "er",
    type: "suffix",
    definition: "one who; person connected with",
    examples: ["teacher"],
  },
  {
    label: "-or",
    value: "or",
    type: "suffix",
    definition: "one who; person connected with",
    examples: ["professor"],
  },
  {
    label: "-er",
    value: "er",
    type: "suffix",
    definition: "more",
    examples: ["taller"],
  },
  {
    label: "-est",
    value: "est",
    type: "suffix",
    definition: "the most",
    examples: ["tallest"],
  },
  {
    label: "-ful",
    value: "ful",
    type: "suffix",
    definition: "full of",
    examples: ["helpful"],
  },
  {
    label: "-ic",
    value: "ic",
    type: "suffix",
    definition: "having characteristics of",
    examples: ["poetic"],
  },
  {
    label: "-ing",
    value: "ing",
    type: "suffix",
    definition: "verb forms; present participles",
    examples: ["sleeping"],
  },
  {
    label: "-ion",
    value: "ion",
    type: "suffix",
    definition: "act; process",
    examples: ["submission"],
  },
  {
    label: "-tion",
    value: "tion",
    type: "suffix",
    definition: "act; process",
    examples: ["motion"],
  },
  {
    label: "-ation",
    value: "ation",
    type: "suffix",
    definition: "act; process",
    examples: ["relation"],
  },
  {
    label: "-ition",
    value: "ition",
    type: "suffix",
    definition: "act; process",
    examples: ["edition"],
  },
  {
    label: "-ity",
    value: "ity",
    type: "suffix",
    definition: "state of",
    examples: ["activity"],
  },
  {
    label: "-ty",
    value: "ty",
    type: "suffix",
    definition: "state of",
    examples: ["society"],
  },
  {
    label: "-ive",
    value: "ive",
    type: "suffix",
    definition: "adjective form of noun",
    examples: ["active"],
  },
  {
    label: "-ative",
    value: "ative",
    type: "suffix",
    definition: "adjective form of noun",
    examples: ["comparative"],
  },
  {
    label: "-itive",
    value: "itive",
    type: "suffix",
    definition: "adjective form of noun",
    examples: ["sensitive"],
  },
  {
    label: "-less",
    value: "less",
    type: "suffix",
    definition: "without",
    examples: ["hopeless"],
  },
  {
    label: "-ly",
    value: "ly",
    type: "suffix",
    definition: "how something is",
    examples: ["lovely"],
  },
  {
    label: "-ment",
    value: "ment",
    type: "suffix",
    definition: "state of being; act of",
    examples: ["contentment"],
  },
  {
    label: "-ness",
    value: "ness",
    type: "suffix",
    definition: "state of; condition of",
    examples: ["openness"],
  },
  {
    label: "-ous",
    value: "ous",
    type: "suffix",
    definition: "having qualities of",
    examples: ["riotous"],
  },
  {
    label: "-eous",
    value: "eous",
    type: "suffix",
    definition: "having qualities of",
    examples: ["courageous"],
  },
  {
    label: "-ious",
    value: "ious",
    type: "suffix",
    definition: "having qualities of",
    examples: ["gracious"],
  },
  {
    label: "-s",
    value: "s",
    type: "suffix",
    definition: "more than one",
    examples: ["trains"],
  },
  {
    label: "-es",
    value: "es",
    type: "suffix",
    definition: "more than one",
    examples: ["trenches"],
  },
  {
    label: "-y",
    value: "y",
    type: "suffix",
    definition: "characterized by",
    examples: ["gloomy"],
  },
];
